# frozen_string_literal: true

# Which organizations the seeds target.
#
# By default these are the usual Hooli fixtures, with their fixed UUIDs and API
# keys: "Hooli", "Hooli Clickhouse" when LAGO_CLICKHOUSE_ENABLED is set, and the
# "Hooli v2" product catalog organization.
#
# Set LAGO_SEED_ORGS to seed other organizations instead — useful to create
# throwaway organizations on a shared environment without touching the Hooli
# fixtures:
#
#   LAGO_SEED_ORGS="Acme,Globex" bundle exec rails db:seed
#
# Overridden organizations are looked up (or created) by name, get a random UUID
# and a random API key, and are seeded with the same data as Hooli. The product
# catalog organization is skipped unless LAGO_SEED_ORG_CATALOG is set too, so
# LAGO_SEED_ORGS="Acme,Globex" creates exactly two organizations.
#
# Re-running the seeds with the same names reuses the existing organizations and
# keeps the API keys generated by the first run.
module SeedOrganizations
  HOOLI = {
    name: "Hooli",
    id: "11111111-2222-3333-4444-555555555555",
    api_key: "lago_key-hooli-1234567890",
    billing_entity_name: "Hooli",
    billing_entity_code: "hooli",
    clickhouse_events_store: false
  }.freeze

  HOOLI_CLICKHOUSE = {
    name: "Hooli Clickhouse",
    id: "22222222-3333-4444-5555-666666666666",
    api_key: "lago_key-hooli-clickhouse-1234567890",
    billing_entity_name: "Hooli",
    billing_entity_code: "hooli",
    clickhouse_events_store: true
  }.freeze

  HOOLI_V2 = {
    name: "Hooli v2",
    id: "33333333-4444-5555-6666-777777777777",
    api_key: "lago_key-hooli-v2-1234567890",
    billing_entity_name: "Hooli v2",
    billing_entity_code: "hooli_v2",
    clickhouse_events_store: false
  }.freeze

  class << self
    # True when LAGO_SEED_ORGS overrides the Hooli fixtures.
    def custom?
      names.any?
    end

    # Attributes of the organizations seeded by 01_base.rb, in order.
    def configs
      @configs ||= custom? ? names.map { |name| custom_config(name) } : default_configs
    end

    # Attributes of the product catalog (v2) organization, or nil when it should
    # not be seeded.
    def product_catalog_config
      return @product_catalog_config if defined?(@product_catalog_config)

      @product_catalog_config = if catalog_name.present?
        custom_config(catalog_name)
      elsif !custom?
        HOOLI_V2
      end
    end

    # Yields every seeded organization, along with its config. Raises when
    # 01_base.rb has not run yet.
    def each
      return to_enum(:each) unless block_given?

      configs.each { |config| yield find!(config), config }
    end

    def find!(config)
      Organization.find_by!(name: config[:name])
    end

    private

    def names
      @names ||= ENV["LAGO_SEED_ORGS"].to_s.split(",").map(&:strip).reject(&:empty?)
    end

    def catalog_name
      ENV["LAGO_SEED_ORG_CATALOG"].to_s.strip
    end

    def default_configs
      clickhouse? ? [HOOLI, HOOLI_CLICKHOUSE] : [HOOLI]
    end

    # Custom organizations get a random id, and a nil API key so that ApiKey
    # generates a random value for them.
    def custom_config(name)
      {
        name:,
        id: SecureRandom.uuid,
        api_key: nil,
        billing_entity_name: name,
        billing_entity_code: name.parameterize(separator: "_"),
        clickhouse_events_store: clickhouse?
      }
    end

    def clickhouse?
      ENV["LAGO_CLICKHOUSE_ENABLED"] == "true"
    end
  end
end
