# frozen_string_literal: true

module Currencies
  extend ActiveSupport::Concern

  ACCEPTED_CURRENCIES = {
    AED: 'United Arab Emirates dirham',
    AFN: 'Afghan afghani',
    ALL: 'Albanian lek',
    AMD: 'Armenian dram',
    ANG: 'Netherlands Antillean guilder',
    AOA: 'Angolan kwanza',
    ARS: 'Argentine peso',
    AUD: 'Australian dollar',
    AWG: 'Aruban florin',
    AZN: 'Azerbaijani manat',
    BAM: 'Bosnia and Herzegovina convertible mark',
    BBD: 'Barbados dollar',
    BDT: 'Bangladeshi taka',
    BGN: 'Bulgarian lev',
    BIF: 'Bahraini dinar',
    BMD: 'Burundian franc',
    BND: 'Bermudian dollar',
    BOB: 'Brunei dollar',
    BRL: 'Boliviano',
    BSD: 'Brazilian real',
    BWP: 'Bahamian dollar',
    BYN: 'Botswana pula',
    BZD: 'Belarusian ruble',
    CAD: 'Belize dollar',
    CDF: 'Canadian dollar',
    CHF: 'Congolese franc',
    CLP: 'Swiss franc',
    CNY: 'Chilean peso',
    COP: 'Colombian peso',
    CRC: 'Costa Rican colon',
    CVE: 'Cape Verdean escudo',
    CZK: 'Czech koruna',
    DJF: 'Djiboutian franc',
    DKK: 'Danish krone',
    DOP: 'Dominican peso',
    DZD: 'Algerian dinar',
    EGP: 'Egyptian pound',
    ETB: 'Ethiopian birr',
    EUR: 'Euro',
    FJD: 'Fiji dollar',
    FKP: 'Falkland Islands pound',
    GBP: 'Pound sterling',
    GEL: 'Georgian lari',
    GIP: 'Gibraltar pound',
    GMD: 'Gambian dalasi',
    GNF: 'Guinean franc',
    GTQ: 'Guatemalan quetzal',
    GYD: 'Guyanese dollar',
    HKD: 'Hong Kong dollar',
    HNL: 'Honduran lempira',
    HRK: 'Croatian kuna',
    HTG: 'Haitian gourde',
    HUF: 'Hungarian forint',
    IDR: 'Indonesian Rupiah',
    ILS: 'Israeli new shekel',
    INR: 'Indian rupee',
    ISK: 'Icelandic króna',
    JMD: 'Jamaican dollar',
    JPY: 'Japanese yen',
    KES: 'Kenyan shilling',
    KGS: 'Kyrgyzstani som',
    KHR: 'Cambodian riel',
    KMF: 'Comoro franc',
    KRW: 'South Korean won',
    KYD: 'Cayman Islands dollar',
    KZT: 'Kazakhstani tenge',
    LAK: 'Lao kip',
    LBP: 'Lebanese pound',
    LKR: 'Sri Lankan rupee',
    LRD: 'Liberian dollar',
    LSL: 'Lesotho loti',
    MAD: 'Moroccan dirham',
    MDL: 'Moldovan leu',
    MGA: 'Malagasy ariary',
    MKD: 'Macedonian denar',
    MMK: 'Myanmar kyat',
    MNT: 'Mongolian tögrög',
    MOP: 'Macanese pataca',
    MRO: 'Mauritanian ouguiya',
    MUR: 'Mauritian rupee',
    MVR: 'Maldivian rufiyaa',
    MWK: 'Malawian kwacha',
    MXN: 'Mexican peso',
    MYR: 'Malaysian ringgit',
    MZN: 'Mozambican metical',
    NAD: 'Namibian dollar',
    NGN: 'Nigerian naira',
    NIO: 'Nicaraguan córdoba',
    NOK: 'Norwegian Krone',
    NPR: 'Nepalese rupee',
    NZD: 'New Zealand dollar',
    PAB: 'Panamanian balboa',
    PEN: 'Peruvian sol',
    PGK: 'Papua New Guinean kina',
    PHP: 'Philippine peso',
    PKR: 'Pakistani rupee',
    PLN: 'Polish złoty',
    PYG: 'Paraguayan guaraní',
    QAR: 'Qatari riyal',
    RON: 'Romanian leu',
    RSD: 'Serbian dinar',
    RUB: 'Russian ruble',
    RWF: 'Rwandan franc',
    SAR: 'Saudi riyal',
    SBD: 'Solomon Islands dollar',
    SCR: 'Seychelles rupee',
    SEK: 'Swedish Krona',
    SGD: 'Singapore dollar',
    SHP: 'Saint Helena pound',
    SLL: 'Sierra Leonean leone',
    SOS: 'Somali shilling',
    SRD: 'Surinamese dollar',
    STD: 'São Tomé and Príncipe dobra',
    SZL: 'Swazi lilangeni',
    THB: 'Thai baht',
    TJS: 'Tajikistani somoni',
    TOP: 'Tongan paʻanga',
    TRY: 'Turkish lira',
    TTD: 'Trinidad and Tobago dollar',
    TWD: 'New Taiwan dollar',
    TZS: 'Tanzanian shilling',
    UAH: 'Ukrainian hryvnia',
    UGX: 'Ugandan shilling',
    USD: 'American Dollar',
    UYU: 'Uruguayan peso',
    UZS: 'Uzbekistan som',
    VND: 'Vietnamese đồng',
    VUV: 'Vanuatu vatu',
    WST: 'Samoan tala',
    XAF: 'CFA franc BEAC',
    XCD: 'East Caribbean dollar',
    XOF: 'CFA franc BCEAO',
    XPF: 'CFP franc (franc Pacifique)',
    YER: 'Yemeni rial',
    ZAR: 'South African rand',
    ZMW: 'Zambian kwacha',
  }.freeze

  included do
    def self.currency_list
      ACCEPTED_CURRENCIES.keys.map(&:to_s).map(&:upcase)
    end
  end
end
