require:
  - standard
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety
  - rubocop-graphql

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: disable
  DisplayStyleGuide: true
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/*_schema.rb'

# TODO: Enable when we have time to fix all the offenses
Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInBlockArgs:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Performance/CaseWhenSplat:
  Enabled: true

Rails/InverseOf:
  Description: 'Checks for associations where the inverse cannot be determined automatically.'
  Enabled: false

Rails/HttpStatus:
  Description: 'Enforces use of symbolic or numeric value to describe HTTP status.'
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Description: 'Forces a "dependent" options for has_one and has_many rails relations.'
  Enabled: false

RSpec/ExampleLength:
  Description: 'Checks for long examples.'
  Enabled: false

RSpec/MultipleExpectations:
  Description: 'Checks if examples contain too many expect calls.'
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

# GraphQL

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/ExtractType:
  Enabled: false

GraphQL/ExtractInputType:
  Exclude:
    - 'app/graphql/mutations/applied_coupons/create.rb'
    - 'app/graphql/mutations/credit_notes/create.rb'
    - 'app/graphql/mutations/invites/accept.rb'
    - 'app/graphql/mutations/plans/create.rb'
    - 'app/graphql/mutations/plans/update.rb'
    - 'app/graphql/mutations/register_user.rb'
    - 'app/graphql/mutations/wallet_transactions/create.rb'
