FROM ruby:4.0.1-slim

WORKDIR /app
ENV POSTGRES_VERSION=15

RUN apt update -qq && \
  apt-get install nodejs build-essential curl git pkg-config libpq-dev libclang-dev postgresql-common libyaml-dev libreadline-dev -y && \
  curl https://sh.rustup.rs -sSf | bash -s -- -y && \
  /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -i -v $POSTGRES_VERSION

RUN curl -L https://github.com/pdfcpu/pdfcpu/releases/download/v0.11.0/pdfcpu_0.11.0_Linux_arm64.tar.xz -o pdfcpu.tar.xz \
    && tar -xf pdfcpu.tar.xz \
    && install -m 755 pdfcpu_0.11.0_Linux_arm64/pdfcpu /usr/local/bin/ \
    && rm -rf pdfcpu.tar.xz pdfcpu_0.11.0_Linux_arm64

ENV BUNDLER_VERSION='2.6.8'
ENV PATH="$PATH:/root/.cargo/bin/"

COPY ./Gemfile /app/Gemfile
COPY ./Gemfile.lock /app/Gemfile.lock

RUN gem install bundler --no-document -v '4.0.4'

RUN bundle config set build.nokogiri --use-system-libraries && \
  bundle install

CMD ["./scripts/start.dev.sh"]
