# This Docker Compose file is to use for CI purposes only
# At Lago we use it to run ours integrations tests

version: "3.8"

volumes:
  lago_api_data:

services:
  db:
    image: postgres:14.0-alpine
    container_name: lago-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lago
      POSTGRES_USER: lago
      POSTGRES_PASSWORD: lago
      PGDATA: /data/postgres
    volumes:
      - lago_postgres_data:/data/postgres
    ports:
      - 5432:5432
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
  
  api:
    image: getlago/api:ci
    container_name: lago-api
    restart: unless-stopped
    depends_on: 
      - "db"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://lago:lago@db:5432/lago
      SECRET_KEY_BASE: secret-key
      LAGO_RSA_PRIVATE_KEY: ${LAGO_RSA_PRIVATE_KEY}
      LAGO_DISABLE_SEGMENT: true