FROM ruby:3.3.4-slim

WORKDIR /app

RUN apt update -qq && \
  apt install nodejs build-essential curl git pkg-config libpq-dev libclang-dev -y && \
  curl https://sh.rustup.rs -sSf | bash -s -- -y

ENV BUNDLER_VERSION='2.5.5'
ENV PATH="$PATH:/root/.cargo/bin/"

COPY ./Gemfile /app/Gemfile
COPY ./Gemfile.lock /app/Gemfile.lock

RUN gem install bundler --no-document -v '2.5.5'

RUN bundle config build.nokogiri --use-system-libraries && \
  bundle install

CMD ["./scripts/start.dev.sh"]
