# frozen_string_literal: true

module Taxes
  class AutoGenerateService < BaseService
    def initialize(organization:)
      @organization = organization

      super
    end

    def call
      lago_eu_vat = LagoEuVat.new
      countries = lago_eu_vat.countries

      countries.each do |country_code|
        create_country_tax(country_code)
      end

      create_generic_taxes
    end

    private

    attr_reader :organization

    def create_country_tax(country_code)
      country_rates = lago_eu_vat.country_rates(country_code)
      tax_code = "lago_eu_#{country_code.downcase}_standard"
      create_tax(tax_code, country_rates['standard'])
    end

    def create_generic_taxes
      create_tax('lago_eu_reverse_charge', 0.0)
      create_tax('lago_eu_tax_exempt', 0.0)
    end

    def create_tax(tax_code, rate)
      tax = organization.taxes.find_or_initialize_by(
        code: tax_code,
      )

      tax.name = tax_code.humanize
      tax.rate = rate
      tax.description = 'Generated By Lago EU VAT management'

      tax.save!
    end
  end
end
