multiple_payment_methods:
  description: "Allow multiple payment methods per customer"
  owners: ["@lovrocolic", "@mariohd"]

non_persistable_charge_cache_optimization:
  description: "Optimize current usage cache by not storing non-persistable fees (zero units/amounts/events)"
  owners: ["@groyoh"]

postgres_enriched_events:
  description: "Turn on events pre-enrichement for organizations using the PG event store"
  owners: ["@vincent-pochet"]

enriched_events_aggregation:
  description: "Use the enriched events store for aggregation queries in ClickHouse"
  owners: ["@vincent-pochet"]

wallet_traceability:
  description: "Enable wallet traceability on newly created wallets"
  owners: ["@groyoh", "@D1353L"]

multi_currency:
  description: "Allow customers to have billing objects in multiple currencies"
  owners: ["@feliperodrigues", "@mariohd", "@lovrocolic"]

payment_gated_subscriptions:
  description: "Enable payment-gated subscription activation rules"
  owners: ["@osmarluz", "@ancorcruz"]

quote:
  description: "Enable the Quotes product"
  owners: ["@murparreira", "@toommz", "@rinasergeeva"]
