blank_issues_enabled: false
contact_links:
  - name: Lago Community
    url: https://www.getlago.com/slack
    about: Join us on Slack to get answers to your questions and submit new feature requests.
