default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "pdfs"
      threads: <%= ENV.fetch("JOB_CONCURRENCY", 10) %>
      processes: 1
      polling_interval: 3

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
