default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues:
        - default
        - mailers
        - clock
        - providers
        - billing
        - webhook
        - invoices
        - wallets
        - integrations
      threads: <%= ENV.fetch("JOB_CONCURRENCY", 10) %>
      processes: 1
      polling_interval: 0.1
    - queues: "low_priority"
      threads: <%= ENV.fetch("JOB_CONCURRENCY", 10) %>
      processes: 1
      polling_interval: 3

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
