default: &default
  activate_subscriptions:
    class: Clock::ActivateSubscriptionsJob
    queue: clock
    schedule: every 5 minutes

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
