# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: books.proto for package 'books'

require 'grpc'
require 'books_pb'

module Books
  module BookService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'books.BookService'

      rpc :GetBooks, ::Books::EmptyParams, ::Books::Books
      rpc :GetBook, ::Books::BookID, ::Books::Book
    end

    Stub = Service.rpc_stub_class
  end
end
