# This Docker Compose file is to use for CI purposes only
# At Lago we use it to run ours integrations tests

version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
